spring:
  application:
    name: ds
  redis:
    host: redis-17106.c261.us-east-1-4.ec2.cloud.redislabs.com
    port: 17106
    password: MQrUFccuQ269fbqIPsRqx1CjmHjcepza
    time-out: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: wlstldbs1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.naver.com
    port: 465
    username: shgurtns7236
    password: pynn2409!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true
          ssl:
            enable: true

jwt:
  access-secret: zdeRaZg/EiMrAVuOX6pZeU5cdas5VqExPhTGje3dzIw=
  refresh-secret: 3Koh9ZqwkJOkjTSe1Y9k+r1gnTo8C5gPlAckjufNQYQ=

server:
  port: 8080
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: dss3-bucket
      url: https://dss3-bucket.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-Key: AKIARR5DC36KBXT2LFLV
      secret-Key: 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


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
        exclude:
      base-path: /management
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}